// Code generated by mockery v2.53.5. DO NOT EDIT.

package startup

import (
	connector "github.com/backtesting-org/kronos-sdk/pkg/types/connector"
	mock "github.com/stretchr/testify/mock"

	portfolio "github.com/backtesting-org/kronos-sdk/pkg/types/portfolio"
)

// Startup is an autogenerated mock type for the Startup type
type Startup struct {
	mock.Mock
}

type Startup_Expecter struct {
	mock *mock.Mock
}

func (_m *Startup) EXPECT() *Startup_Expecter {
	return &Startup_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with given fields: strategyPath, connectors, assets
func (_m *Startup) Start(strategyPath string, connectors map[connector.ExchangeName]connector.Config, assets map[portfolio.Asset][]connector.Instrument) error {
	ret := _m.Called(strategyPath, connectors, assets)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[connector.ExchangeName]connector.Config, map[portfolio.Asset][]connector.Instrument) error); ok {
		r0 = rf(strategyPath, connectors, assets)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Startup_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Startup_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - strategyPath string
//   - connectors map[connector.ExchangeName]connector.Config
//   - assets map[portfolio.Asset][]connector.Instrument
func (_e *Startup_Expecter) Start(strategyPath interface{}, connectors interface{}, assets interface{}) *Startup_Start_Call {
	return &Startup_Start_Call{Call: _e.mock.On("Start", strategyPath, connectors, assets)}
}

func (_c *Startup_Start_Call) Run(run func(strategyPath string, connectors map[connector.ExchangeName]connector.Config, assets map[portfolio.Asset][]connector.Instrument)) *Startup_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[connector.ExchangeName]connector.Config), args[2].(map[portfolio.Asset][]connector.Instrument))
	})
	return _c
}

func (_c *Startup_Start_Call) Return(_a0 error) *Startup_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Startup_Start_Call) RunAndReturn(run func(string, map[connector.ExchangeName]connector.Config, map[portfolio.Asset][]connector.Instrument) error) *Startup_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *Startup) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Startup_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Startup_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Startup_Expecter) Stop() *Startup_Stop_Call {
	return &Startup_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Startup_Stop_Call) Run(run func()) *Startup_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Startup_Stop_Call) Return(_a0 error) *Startup_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Startup_Stop_Call) RunAndReturn(run func() error) *Startup_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewStartup creates a new instance of Startup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStartup(t interface {
	mock.TestingT
	Cleanup(func())
}) *Startup {
	mock := &Startup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
